stage2: testbench-LEGLiteSingle-Stage2.V LEGLite-PC.V LEGLite-Parts.V LEGLite-Single.V LEGLite-Control.V IM1.V
	veriwell testbench-LEGLiteSingle-Stage2.V LEGLite-PC.V LEGLite-Parts.V LEGLite-Single.V LEGLite-Control.V IM1.V
stage3: testbench-LEGLiteSingle-Stage3.V LEGLite-PC.V LEGLite-Parts.V LEGLite-Single.V LEGLite-Control.V IM2.V
	veriwell testbench-LEGLiteSingle-Stage3.V LEGLite-PC.V LEGLite-Parts.V LEGLite-Single.V LEGLite-Control.V IM2.V
control: testbench-Control.V LEGLite-Control.V
	veriwell testbench-Control.V LEGLite-Control.V
pc: testbench-PC.V LEGLite-PC.V
	veriwell testbench-PC.V LEGLite-PC.V
parts: testbench-Parts-CombCirc.V LEGLite-Parts.V
	veriwell testbench-Parts-CombCirc.V LEGLite-Parts.V
dmem: testbench-Parts-Dmem.V LEGLite-Parts.V
	veriwell testbench-Parts-Dmem.V LEGLite-Parts.V
rfile: testbench-Parts-RFile.V LEGLite-Parts.V
	veriwell testbench-Parts-RFile.V LEGLite-Parts.V
